# -*- coding: utf-8 -*-
"""GenAiCoursework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1meZr_RTHz7KE7mJBAiz6_w7FUxqSh_3d
"""

!pip -q install -U bitsandbytes>=0.46.1

import os, json, time, gc, platform
from datetime import datetime
import torch

RUN_NAME = f"gemma2-2b-xsum-lora-vs-qlora-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
OUTPUT_DIR = f"/content/{RUN_NAME}"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def gpu_info():
    info = {
        "torch_version": torch.__version__,
        "cuda_available": torch.cuda.is_available(),
        "platform": platform.platform(),
        "python": platform.python_version(),
    }
    if torch.cuda.is_available():
        info.update({
            "gpu_name": torch.cuda.get_device_name(0),
            "vram_gb": round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
            "bf16_supported": torch.cuda.is_bf16_supported(),
        })
    return info

info = gpu_info()
print(info)

with open(os.path.join(OUTPUT_DIR, "hardware_env.json"), "w") as f:
    json.dump(info, f, indent=2)

def reset_cuda_stats():
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

def peak_mem_gb():
    if torch.cuda.is_available():
        return round(torch.cuda.max_memory_allocated() / 1024**3, 3)
    return None

print("Run folder:", OUTPUT_DIR)
if torch.cuda.is_available():
    print("Free/Total GB:", [round(x/1024**3,2) for x in torch.cuda.mem_get_info()])

"""#**Load Xsum Subset**"""

from datasets import load_dataset

ds = load_dataset("xsum")

# Start modest for speed; scale later if you have time
TRAIN_N = 2000
VAL_N   = 300
TEST_N  = 300

train_ds = ds["train"].shuffle(seed=42).select(range(TRAIN_N))
val_ds   = ds["validation"].shuffle(seed=42).select(range(VAL_N))
test_ds  = ds["test"].shuffle(seed=42).select(range(TEST_N))

print("Sizes:", len(train_ds), len(val_ds), len(test_ds))
print(train_ds[0].keys())

"""#**Prompt + Preprocessing**"""

def build_prompt(document: str) -> str:
    return (
        "You are a helpful assistant.\n"
        "Summarize the following news article in one concise paragraph.\n\n"
        "ARTICLE:\n"
        f"{document}\n\n"
        "SUMMARY:\n"
    )

def format_sft_example(example):
    prompt = build_prompt(example["document"])
    target = example["summary"].strip()
    return {"text": prompt + target}

"""#**Metrix (Rouge) +Generation Helper**"""

!pip install evaluate rouge_score

import evaluate
rouge = evaluate.load("rouge")

def compute_rouge(preds, refs):
    # evaluate library returns rouge1/rouge2/rougeL/rougeLsum (F1 by default)
    return rouge.compute(predictions=preds, references=refs, use_stemmer=True)

def safe_decode(tokenizer, ids):
    return tokenizer.decode(ids, skip_special_tokens=True)

def extract_after_summary(text: str) -> str:
    if "SUMMARY:" in text:
        return text.split("SUMMARY:", 1)[-1].strip()
    return text.strip()

"""#**Utility: trainable params summary + logging**"""

def param_summary(model):
    total = 0
    trainable = 0
    for p in model.parameters():
        n = p.numel()
        total += n
        if p.requires_grad:
            trainable += n
    pct = 100.0 * trainable / total if total else 0.0
    return {"total_params": total, "trainable_params": trainable, "trainable_pct": pct}

def save_json(name, obj):
    path = os.path.join(OUTPUT_DIR, name)
    with open(path, "w") as f:
        json.dump(obj, f, indent=2)
    print("Saved:", path)

def cleanup(model=None, tokenizer=None):
    try:
        if model is not None:
            del model
        if tokenizer is not None:
            del tokenizer
    except:
        pass
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

"""#**Load model/tokenizer (function supports QLoRA or LoRA)**"""

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_NAME = "google/gemma-2-2b-it"

def load_model(quant_mode: str):
    """
    quant_mode: "qlora4bit" or "lora16bit"
    """
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

    if quant_mode == "qlora4bit":
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float16,
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            quantization_config=bnb_config,
            device_map="auto",
            torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float16,
            low_cpu_mem_usage=True, # Added for memory efficiency
        )
    elif quant_mode == "lora16bit":
        # No 4bit quantization; will be heavier on VRAM
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            device_map="auto",
            torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float16,
            low_cpu_mem_usage=True, # Added for memory efficiency
        )
    else:
        raise ValueError("quant_mode must be 'qlora4bit' or 'lora16bit'")

    model.config.use_cache = False
    return model, tokenizer

print("Ready.")

"""#**Generation + EVALUATION loop**"""

@torch.no_grad()
def generate_one(model, tokenizer, prompt, max_new_tokens=60):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=768).to(model.device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        num_beams=1,  # greedy decode (FAST)
        repetition_penalty=1.1,
        pad_token_id=tokenizer.eos_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )
    text = safe_decode(tokenizer, out[0])
    return extract_after_summary(text)

def eval_on_test(model, tokenizer, dataset, limit=50, tag=""):
    reset_cuda_stats()
    preds, refs = [], []
    for i in range(min(limit, len(dataset))):
        doc = dataset[i]["document"]
        ref = dataset[i]["summary"]
        pred = generate_one(model, tokenizer, build_prompt(doc))
        preds.append(pred)
        refs.append(ref)
        if (i+1) % 10 == 0:
            print(f"[{tag}] {i+1}/{min(limit, len(dataset))} done")
    scores = compute_rouge(preds, refs)
    mem = peak_mem_gb()
    return scores, mem, preds, refs

"""#**Baseline (No Fine Tuning) Rouge**"""

model_base, tok_base = load_model("qlora4bit")
model_base.eval()

BASELINE_LIMIT = 30  # faster for iteration
baseline_scores, baseline_mem, baseline_preds, baseline_refs = eval_on_test(
    model_base, tok_base, test_ds, limit=BASELINE_LIMIT, tag="BASELINE"
)

print("Baseline ROUGE:", baseline_scores)
print("Baseline peak VRAM GB:", baseline_mem)

save_json("baseline_rouge.json", baseline_scores)
save_json("baseline_meta.json", {"limit": BASELINE_LIMIT, "peak_vram_gb": baseline_mem, "mode":"4bit_inference"})

"""#Prepare SFT datasets for training"""

train_sft = train_ds.map(format_sft_example, remove_columns=train_ds.column_names)
val_sft   = val_ds.map(format_sft_example, remove_columns=val_ds.column_names)

print(train_sft[0]["text"][:400])

"""#**Train QLoRA (PEFT) with TRL SFTTrainer**"""

!pip install trl

import os, time, gc
import torch
import trl
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer
from transformers import TrainingArguments

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

# Clean up baseline model
cleanup(model_base, tok_base)
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# Load 4-bit model for QLoRA
model_q, tok_q = load_model("qlora4bit")
model_q = prepare_model_for_kbit_training(model_q)

# Define max sequence length for tokenization
MAX_SEQ_LENGTH = 256

def tokenize_function(examples):
    # This assumes format_sft_example returns {'text': ...}
    # and the prompt is built as before.
    # The format_sft_example already prepares 'text' field.
    return tok_q(
        examples['text'],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding='max_length' # Pad to max_length for consistent input shapes
    )

# First, format the datasets to have the 'text' field
train_sft = train_ds.map(format_sft_example, remove_columns=train_ds.column_names)
val_sft   = val_ds.map(format_sft_example, remove_columns=val_ds.column_names)

# Now, tokenize the formatted datasets with the defined MAX_SEQ_LENGTH
train_tokenized_ds = train_sft.map(tokenize_function, batched=True, remove_columns=['text'])
val_tokenized_ds   = val_sft.map(tokenize_function, batched=True, remove_columns=['text'])

# Smaller LoRA = less VRAM
lora_cfg = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
)
model_q = get_peft_model(model_q, lora_cfg)

q_params = param_summary(model_q)
print("QLoRA param summary:", q_params)
save_json("qlora_param_summary.json", q_params)

reset_cuda_stats()
t0 = time.time()

# Calculate warmup steps based on ratio (using dataset size for calculation)
GRADIENT_ACCUMULATION_STEPS = 8
num_training_steps = int(len(train_tokenized_ds) / (1 * GRADIENT_ACCUMULATION_STEPS) * 1) # (dataset_size / (per_device_train_batch_size * gradient_accumulation_steps)) * num_train_epochs
warmup_steps = int(num_training_steps * 0.03)

args_q = TrainingArguments(
    output_dir=os.path.join(OUTPUT_DIR, "qlora_ckpt"),
    per_device_train_batch_size=1,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=2e-4,
    num_train_epochs=1,
    logging_steps=10,
    eval_strategy="no", # Disable evaluation during training to save VRAM
    # eval_steps=100, # Removed as eval_strategy is "no"
    save_steps=100,
    save_total_limit=2,
    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    report_to="none",
    optim="paged_adamw_8bit",
    lr_scheduler_type="cosine",
    warmup_steps=warmup_steps, # Changed from warmup_ratio
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={'use_reentrant':False}, # Explicitly set use_reentrant
)

trainer_q = SFTTrainer(
    model=model_q,
    # tokenizer=tok_q, # Removed as dataset is pre-tokenized
    train_dataset=train_tokenized_ds,
    eval_dataset=val_tokenized_ds,
    # dataset_text_field="text", # Removed as dataset is pre-tokenized
    # max_seq_length=256, # Removed as dataset is pre-tokenized
    # packing=True,           # Removed as it's not supported in this trl version
    args=args_q,
)

trainer_q.train()

train_time_q = time.time() - t0
peak_train_mem_q = peak_mem_gb()

qlora_adapter_dir = os.path.join(OUTPUT_DIR, "qlora_adapter")
trainer_q.model.save_pretrained(qlora_adapter_dir)
tok_q.save_pretrained(qlora_adapter_dir)

training_args_dict = args_q.to_dict()
# Convert any sets within training_args_dict to lists for JSON serialization
for key, value in training_args_dict.items():
    if isinstance(value, set):
        training_args_dict[key] = list(value)

lora_config_dict = lora_cfg.to_dict()
# Convert any sets within lora_config_dict to lists (though less likely for LoraConfig)
for key, value in lora_config_dict.items():
    if isinstance(value, set):
        lora_config_dict[key] = list(value)

save_json("qlora_train_meta.json", {
    "train_seconds": train_time_q,
    "peak_train_vram_gb": peak_train_mem_q,
    "training_args": training_args_dict,
    "lora_config": lora_config_dict
})

print("QLoRA training done. Time(s):", round(train_time_q, 1), "Peak VRAM(GB):", peak_train_mem_q)

"""#Evaluate QLoRA ROUGE"""

trainer_q.model.eval()

qlora_scores, qlora_eval_mem, qlora_preds, qlora_refs = eval_on_test(
    trainer_q.model, tok_q, test_ds, limit=BASELINE_LIMIT, tag="QLORA"
)

print("QLoRA ROUGE:", qlora_scores)
print("QLoRA eval peak VRAM GB:", qlora_eval_mem)

save_json("qlora_rouge.json", qlora_scores)
save_json("qlora_eval_meta.json", {"limit": BASELINE_LIMIT, "peak_vram_gb": qlora_eval_mem, "mode":"QLoRA"})

"""## Qualitative examples (Baseline vs QLoRA only)"""

# CELL 14 — Qualitative examples (Baseline vs QLoRA only)
import pandas as pd, random, os

rows = []
sample_k = 10
limit_used = min(BASELINE_LIMIT, len(baseline_preds), len(qlora_preds))
indices = random.sample(range(limit_used), min(sample_k, limit_used))

for i in indices:
    rows.append({
        "doc_snippet": test_ds[i]["document"][:350].replace("\n"," "),
        "reference": baseline_refs[i],
        "baseline": baseline_preds[i],
        "qlora": qlora_preds[i],
    })

df = pd.DataFrame(rows)
csv_path = os.path.join(OUTPUT_DIR, "qualitative_examples.csv")
df.to_csv(csv_path, index=False)
print("Saved:", csv_path)
df

# CELL 15 — Results table (Baseline vs QLoRA only)
import pandas as pd, os, json

def to_row(name, scores, train_meta=None, params=None):
    row = {"model": name}
    row.update({
        "rouge1": scores.get("rouge1"),
        "rouge2": scores.get("rouge2"),
        "rougeL": scores.get("rougeL"),
        "rougeLsum": scores.get("rougeLsum"),
    })
    if train_meta:
        row.update({
            "train_seconds": train_meta.get("train_seconds"),
            "peak_train_vram_gb": train_meta.get("peak_train_vram_gb"),
        })
    if params:
        row.update({
            "trainable_pct": params.get("trainable_pct"),
            "trainable_params": params.get("trainable_params"),
            "total_params": params.get("total_params"),
        })
    return row

# Load QLoRA meta if you saved them
qlora_train_meta_path = os.path.join(OUTPUT_DIR, "qlora_train_meta.json")
qlora_param_path = os.path.join(OUTPUT_DIR, "qlora_param_summary.json")

qlora_train_meta = json.load(open(qlora_train_meta_path)) if os.path.exists(qlora_train_meta_path) else None
qlora_params = json.load(open(qlora_param_path)) if os.path.exists(qlora_param_path) else None

results = [
    to_row("Baseline (4bit inference)", baseline_scores),
    to_row("QLoRA (4bit + LoRA adapters)", qlora_scores, train_meta=qlora_train_meta, params=qlora_params),
]

df_results = pd.DataFrame(results)
table_path = os.path.join(OUTPUT_DIR, "results_table.csv")
df_results.to_csv(table_path, index=False)
print("Saved:", table_path)
df_results

zip_name = f"{RUN_NAME}.zip"
!zip -r "{zip_name}" "{OUTPUT_DIR}" > /content/zip_log.txt
print("Zipped to:", f"/content/{zip_name}")

!pip -q install -U bert-score
import evaluate

bertscore = evaluate.load("bertscore")

def compute_bertscore(preds, refs):
    out = bertscore.compute(predictions=preds, references=refs, lang="en")
    return {
        "precision": sum(out["precision"]) / len(out["precision"]),
        "recall": sum(out["recall"]) / len(out["recall"]),
        "f1": sum(out["f1"]) / len(out["f1"]),
    }

baseline_bs = compute_bertscore(baseline_preds, baseline_refs)
qlora_bs    = compute_bertscore(qlora_preds, qlora_refs)

save_json("baseline_bertscore.json", baseline_bs)
save_json("qlora_bertscore.json", qlora_bs)

print("Baseline:", baseline_bs)
print("QLoRA:", qlora_bs)

import os, json
import matplotlib.pyplot as plt

# Load saved BERTScore results
baseline_bs = json.load(open(os.path.join(OUTPUT_DIR, "baseline_bertscore.json")))
qlora_bs    = json.load(open(os.path.join(OUTPUT_DIR, "qlora_bertscore.json")))

metrics = ["precision", "recall", "f1"]
baseline_vals = [baseline_bs[m] for m in metrics]
qlora_vals    = [qlora_bs[m] for m in metrics]

x = range(len(metrics))
w = 0.35

plt.figure()
plt.bar([i - w/2 for i in x], baseline_vals, width=w, label="Baseline")
plt.bar([i + w/2 for i in x], qlora_vals, width=w, label="QLoRA")
plt.xticks(list(x), ["BERTScore-P", "BERTScore-R", "BERTScore-F1"])
plt.ylabel("Score")
plt.title("Baseline vs QLoRA — BERTScore on XSum")
plt.legend()
plt.tight_layout()

out_path = os.path.join(OUTPUT_DIR, "bertscore_comparison.png")
plt.savefig(out_path, dpi=200)
plt.show()

print("Saved:", out_path)